name: soundwave
description: Free Hindi,English,Punjabi music

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer: ^0.5.2
  audioplayers: ^1.0.1
#  http: ^0.12.0
  http: ^0.13.5
#  chewie: ^0.8.0
  chewie: ^1.3.4
#  sqflite: ^0.13.0
  sqflite: ^2.0.3+1
#  firebase_core: ^0.2.5
#  firebase_analytics: ^1.0.4
  firebase_analytics: ^9.3.3
#  firebase_database: ^1.0.5
  firebase_database: ^9.1.3
#  firebase_auth: ^0.6.6
  firebase_auth: ^3.7.0
#  flutter_launcher_icons: ^0.7.0
  flutter_launcher_icons: ^0.10.0
#  rxdart: ^0.20.0
  rxdart: ^0.27.5
#  uni_links: ^0.1.4
  uni_links: ^0.5.1
#  shared_preferences: ^0.4.3
  shared_preferences: ^2.0.15
  device_info: ^0.3.0
  device_info_plus: ^4.1.2
#  url_launcher: ^4.0.3
  url_launcher: ^6.1.5
  share: ^0.5.3
  flutter_share: ^2.0.0
  firebase_core: ^1.4.0
# The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/menu.png
   - images/star.png
   - images/collections.png
   - images/home.png
   - images/homeactive.png
   - images/search.png
   - images/searchactive.png
   - images/discover.png
   - images/logo.png
   - images/back_navigation.png
   - images/download.png
   - images/loading.gif
   - images/discoveractive.png
   - images/collections.png
   - images/collectionsactive.png
   - images/profile.png
   - images/profileactive.png
   - images/cover.jpg
   - images/video.png
   - images/downloads.png
   - images/more.png
   - images/share.png
   - images/heart.png
   - images/github.png
   - images/heartactive.png
   - images/more_horizontal.png
   - images/not_interested.png
   - images/settings.png
   - images/music_placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ProximaNova
       fonts:
         - asset: fonts/ProximaNova-Regular.ttf
     - family: GothamBook
       fonts:
         - asset: fonts/GothamBook.ttf
     - family: GoogleSans
       fonts:
         - asset: fonts/GoogleSans.ttf
     - family: ChocoCooky
       fonts:
         - asset: fonts/Chococooky.ttf
                    #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
